import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import favicon from "../public/favicon.ico"
const inter = Inter({ subsets: ['latin'] })
import Navbar from "../components/navbar"


export default function Home() {
  return (
    <>
      <Head>
        <title>krishna-ai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href='/favicon.ico' />

      </Head>
      <main className={styles.main}>
        <div className='navbar'>
          <Navbar></Navbar>
        </div>

      </main>
      <style jsx>
        {`
        
        .navbar{
          width:100%;
          max-width:1800px;
          overflow: hidden;
          position: fixed;
          top: 0;
        }
        `}
      </style>
    </>
  )
}
